server:
  port : 8662
eureka:
  client:
    register-with-eureka : true
    fetch-registry : true
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/
spring :
  application:
    name: gateway-service
  #security :
   # user :
    #  name : user
     # password : user
      #roles : manager

zuul:
  host:
    connection-timeout-millis : 5000000
    socket-timeout-millis : 5000000
  ignoredServices: '*'
  routes :
    registration-service:
      path : /registration/**
      serviceId : registration-service
      stripPrefix : true
